name: Holograms
version: ${project.version}
main: me.jacobtread.holograms.Plugin
author: Jacobtread
description: A Holograms plugin
commands:
  hologram:
    description: Main command for holograms
    aliases: [holo, holograms]
    permission: hologram.main
permissions:
  hologram.main:
    description: Allows use of the plugin
